# Protocolos
STOP_AND_WAIT="stop_and_wait"
SELECTIVE_REPEAT="selective_repeat"
STOP_AND_WAIT_PROTOCOL=0
SELECTIVE_REPEAT_PROTOCOL=1

# Tipos de paquetes (como constantes)
TYPE_DATA = 1
TYPE_ACK = 2
TYPE_CLOSE = 3
TYPE_SYN = 4

PAYLOAD_SIZE = 1400
HEADER_SIZE = 12
BUFFER_SIZE = 1024

OP_TYPE_UPLOAD = 1
OP_TYPE_DOWNLOAD = 0

INFO_FIELD_SIZE = 32
PKT_TYPE_FIELD_SIZE = 3
OP_TYPE_FIELD_SIZE = 1
PROTOCOL_FIELD_SIZE = 1
PAYLOAD_LENGTH_FIELD_SIZE = 27
CRC_FIELD_SIZE = 32
ID_FIELD_SIZE = 32



PKT_TYPE_MASK = 0x7 # not used
PAYLOAD_LENGTH_MASK = 0x7FFFFFF
PROTOCOL_MASK = 0x1
OP_TYPE_MASK = 0x1